import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import Providers from "@/app/Stores/Providers";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <head>
            <meta name="viewport" content="width=device-width, initial-scale=1, interactive-widget=resizes-content"/>
            <title>Weather 2.0</title>
        </head>
        <body className={inter.className + " overflow-clip min-h-lvh"}>
        <Providers>{children}</Providers>
        </body>
        </html>
    );
}
